# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NAVY', 'Navy'), ('ARMY', 'Army'), ('RAAF', 'RAAF'), ('CIV', 'Civilan'), ('GEN', 'General')], max_length=4)),
                ('type', models.CharField(choices=[('ART', 'Art'), ('BOOK', 'Book'), ('DIARY', 'Diary'), ('DISPLAY', 'Display'), ('EQUIPMENT', (('HELMENT', 'Helmet'), ('UNIFORM', 'Uniform')))], max_length=20)),
            ],
        ),
    ]
