# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NAVY', 'Navy'), ('ARMY', 'Army'), ('RAAF', 'RAAF'), ('CIV', 'Civilan'), ('GEN', 'General')], max_length=4)),
                ('type', models.CharField(choices=[('ART', 'Art'), ('BOOK', 'Book'), ('DIARY', 'Diary'), ('DISPLAY', 'Display'), ('EQUIPMENT', 'Equipment'), ('FLAG', 'Flag'), ('WEAPON', 'Weapon'), ('MEDAL', 'Medal'), ('MODEL', 'Model'), ('INSIGNIA', 'Insignia'), ('PLAQUE', 'Plaque'), ('UNIFORM', 'Uniform')], max_length=20)),
                ('location', models.CharField(default=' ', max_length=50)),
                ('era', models.CharField(choices=[('COLONIAL', 'Colonial'), ('BOER', 'Boer War'), ('WW1', 'World War 1'), ('WW2', 'World War 2'), ('KOREA', 'Korean War'), ('VIETNAM', 'Vietnam War'), ('MODERN', 'Post 1975')], default=' ', max_length=15)),
                ('reference', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Art', (('PAINTING', 'Painting'), ('DRAWING', 'Drawing'), ('SCULPTURE', 'Sculpture'), ('POSTER', 'Poster'))), ('Book', (('BOOK', 'Book'), ('MAGAZINE', 'Magazine'), ('JOURNAL', 'Journal'), ('REFERENCE', 'Reference'), ('COMIC', 'Comic'))), ('DIARY', 'Diary'), ('DISPLAY', 'Display'), ('Equipment', (('HELMET', 'Helemet'), ('BINOCULARS', 'Binoculars'), ('CANTEEN', 'Canteen'), ('BAG', 'Bag'), ('PACK', 'Pack'), ('WEBBING', 'Webbing'))), ('FLAG', 'Flag'), ('Weapon', (('AXE', 'Axe'), ('GRENADE', 'Grenade'), ('CANNON', 'Cannon'), ('KNIFE', 'Knife'), 'RIFLERifle', ('PISTOL', 'Pistol'), ('SWORD', 'Sword'), ('DAGGER', 'Dagger'))), ('MEDAL', 'Medal'), ('Model', (('AIRPLANE', 'Airplane'), ('HELICOPTER', 'Helicopter'), ('SHIP', 'Ship'), ('SUBMARINE', 'Submarine'), ('TANK', 'Tank'), ('APC', 'APC'), ('JEEP', 'Jeep'))), ('INSIGNIA', 'Insignia'), ('PLAQUE', 'Plaque'), ('Uniform', (('BOOTS', 'Boots'), ('SOCKS', 'Socks'), ('TROUSERS', 'Trousers'), ('SKIRT', 'Skirt'), ('SHIRT', 'Shirt'), ('JACKET', 'Jacket'), ('TUNIC', 'Tunic'), ('HAT', 'Hat'), ('BELT', 'Belt'), ('BUTTON', 'Button')))], max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('EXCELLENT', 'Excellent'), ('VERYGOOD', 'Very Good'), ('AVERAGE', 'Average'), ('BELOWAVERAGE', 'Below Average'), ('POOR', 'Poor')], max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('collection_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museum.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Item')),
            ],
        ),
    ]
