# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='era',
            field=models.CharField(choices=[('COLONIAL', 'Colonial'), ('BOER', 'Boer War'), ('WW1', 'World War 1'), ('WW2', 'World War 2'), ('KOREA', 'Korean War'), ('VIETNAM', 'Vietnam War'), ('MODERN', 'Post 1975')], default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='collection',
            name='location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('ART', 'Art'), ('BOOK', 'Book'), ('DIARY', 'Diary'), ('DISPLAY', 'Display'), ('EQUIPMENT', 'Equipment'), ('FLAG', 'Flag'), ('WEAPON', 'Weapon'), ('MEDAL', 'Medal'), ('MODEL', 'Model'), ('INSIGNIA', 'Insignia'), ('PLAQUE', 'Plaque')], max_length=20),
        ),
        migrations.AddField(
            model_name='collectionimage',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Collection'),
        ),
    ]
