# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Art', (('PAINTING', 'Painting'), ('DRAWING', 'Drawing'), ('SCULPTURE', 'Sculpture'), ('POSTER', 'Poster'))), ('Book', (('BOOK', 'Book'), ('MAGAZINE', 'Magazine'), ('JOURNAL', 'Journal'), ('REFERENCE', 'Reference'), ('COMIC', 'Comic'))), ('DIARY', 'Diary'), ('DISPLAY', 'Display'), ('Equipment', (('HELMET', 'Helemet'), ('BINOCULARS', 'Binoculars'), ('CANTEEN', 'Canteen'), ('BAG', 'Bag'), ('PACK', 'Pack'), ('WEBBING', 'Webbing'))), ('Weapon', (('AXE', 'Axe'), ('GRENADE', 'Grenade'), ('CANNON', 'Cannon'), ('KNIFE', 'Knife'), ('RIFLE', 'Rifle'), ('PISTOL', 'Pistol'), ('SWORD', 'Sword'), ('DAGGER', 'Dagger'))), ('FLAG', 'Flag'), ('MEDAL', 'Medal'), ('Model', (('AIRPLANE', 'Airplane'), ('HELICOPTER', 'Helicopter'), ('SHIP', 'Ship'), ('SUBMARINE', 'Submarine'), ('TANK', 'Tank'), ('APC', 'APC'), ('JEEP', 'Jeep'))), ('INSIGNIA', 'Insignia'), ('PLAQUE', 'Plaque'), ('Uniform', (('BOOTS', 'Boots'), ('SOCKS', 'Socks'), ('TROUSERS', 'Trousers'), ('SKIRT', 'Skirt'), ('SHIRT', 'Shirt'), ('JACKET', 'Jacket'), ('TUNIC', 'Tunic'), ('HAT', 'Hat'), ('BELT', 'Belt'), ('BUTTON', 'Button')))], max_length=20),
        ),
    ]
