# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20170119_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='reference',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='collection',
            name='era',
            field=models.CharField(choices=[('COLONIAL', 'Colonial'), ('BOER', 'Boer War'), ('WW1', 'World War 1'), ('WW2', 'World War 2'), ('KOREA', 'Korean War'), ('VIETNAM', 'Vietnam War'), ('MODERN', 'Post 1975')], default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
