# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_collection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='era',
            field=models.CharField(choices=[('Colonial', 'Colonial'), ('Boer War', 'Boer War'), ('WW1', 'World War 1'), ('WW2', 'World War 2'), ('Korean War', 'Korean War'), ('Vietnam War', 'Vietnam War'), ('Post 1975', 'Post 1975')], default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('Art', 'Art'), ('Book', 'Book'), ('Diary', 'Diary'), ('Display', 'Display'), ('Equipment', 'Equipment'), ('Flag', 'Flag'), ('Weapon', 'Weapon'), ('Medal', 'Medal'), ('Modern', 'Model'), ('Insignia', 'Insignia'), ('Plaque', 'Plaque'), ('Uniform', 'Uniform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Art', (('Painting', 'Painting'), ('Drawing', 'Drawing'), ('Sculpture', 'Sculpture'), ('Poster', 'Poster'))), ('Book', (('Book', 'Book'), ('Magazine', 'Magazine'), ('Journal', 'Journal'), ('Reference', 'Reference'), ('Comic', 'Comic'))), ('Diary', 'Diary'), ('Display', 'Display'), ('Equipment', (('Helmet', 'Helemet'), ('Binoculars', 'Binoculars'), ('Canteen', 'Canteen'), ('Bag', 'Bag'), ('Pack', 'Pack'), ('Webbing', 'Webbing'))), ('Weapon', (('Axe', 'Axe'), ('Grenade', 'Grenade'), ('Cannon', 'Cannon'), ('Knife', 'Knife'), ('Rifle', 'Rifle'), ('Pistol', 'Pistol'), ('Sword', 'Sword'), ('Dagger', 'Dagger'))), ('Flag', 'Flag'), ('Medal', 'Medal'), ('Model', (('Airplane', 'Airplane'), ('Helicopter', 'Helicopter'), ('Ship', 'Ship'), ('Submarine', 'Submarine'), ('Tank', 'Tank'), ('APC', 'APC'), ('Jeep', 'Jeep'))), ('Insignia', 'Insignia'), ('Plaque', 'Plaque'), ('Uniform', (('Boots', 'Boots'), ('Socks', 'Socks'), ('Trousers', 'Trousers'), ('Skirt', 'Skirt'), ('Shirt', 'Shirt'), ('Jacket', 'Jacket'), ('Tunic', 'Tunic'), ('Hat', 'Hat'), ('Belt', 'Belt'), ('Button', 'Button')))], max_length=20),
        ),
    ]
