# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20170127_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='museum/static/museum/database/photo_not_available.png', upload_to='museum/static/museum/database/'),
        ),
    ]
